site_name: MeuPet
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
- Início: index.md
- Requisitos:
    - "Visão e Escopo": requisitos/1.visaoEscopo.md
    - "Identificação de Atores": requisitos/2.identificacao.md
    - "Elicitação de Requisitos": requisitos/3.elicitacao.md
- Arquitetura:
    - "Tecnologias do projeto": arquitetura/tecnologias.md